name: Restart docker compose 

on: 
  workflow_call:
    inputs:
      host:
        required: true
        type: string
      user:
        default: 'ubuntu'
        type: string
      compose_file:
        type: string
        required: true
      branch: 
        type: string
        default: develop
    secrets:
      private_key:
        required: true

jobs: 
  login-restart:
    runs-on: ubuntu-latest
    steps:
      - name: "Login to ${{ inputs.branch == 'develop' && 'STAGGING SERVER' || 'PROD SERVER' }} and restart app"
        run: |
          echo $PRIVATE_KEY > access.pem && chmod 600 access.pem
          echo "Connection..."
          ssh -i access.pem ${{ inputs.user }}@${{ inputs.host}} '
              ([[ ! -d "/home/ubuntu/app"]] && git clone https://${{ secrets.DEPLOY_USER_TOKEN }}@github.com/leuk777/${{ github.repository }}.git app) &&
              cd /home/ubuntu/app &&
              git checkout ${{ inputs.branch }} &&
              git fetch --all &&
              git reset --hard && 
              git pull  &&
              docker compose down && 
              docker compose -f ${{ inputs.compose_file }} up -d &&
              exit
          '

